# 发现导航
在未授权的情况下，您可以免费使用，必须公开可见，禁止商业用途。
# 许可证 GPL-3.0 https://github.com/xjh22222228(nav/blob/main/LICENSE
# 配置信息：https://github.com/xjh22222228(nav?tab=readme-ov-file#%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E
# 网站所有内容都是可以在后台系统配置的，不懂的不要擅自修改源代码，出现异常请自行处理
# Fork 用户通常只需要修改 gitRepoUrl，其他默认处理
# 问题反馈：xjh2222228@gmail.com，非授权不接收功能建议
# 联系授权：https://official.nav3.cn/pricing
# 免责声明：使用即表示已阅读 https://official.nav3.cn/disclaimers

# 仓库地址，填写 Fork 后的仓库地址，支持 Gitee / GitHub / GitLab
# 作者 Gitee 仓库地址 https://gitee.com/xiejiahe/nav
# 作者 GitLab 仓库地址 https://gitlab.com/xjh222228(nav?projectId=68880543, projectId 是项目 ID，可在仓库页面中找到
git库链接：https://github.com/nimabhi12138(nav)

# Fork 部署分支
分支：主分支

# 默认Fork仓库
# 仓库必须自己提前创建，如果打算长期使用本软件，建议每个人都创建一个新的仓库作为图片存储
# 例如 'https://github.com/xjh222228/image?branch=main'
# GitLab 例如 'https://gitlab.com/xjh222228/image?branch=main&projectId=1001'
镜像库网址：''

# 只有GitHub pages用户需要设置为true，其他建议设置为 false
哈希模式：否

# 一旦填写认为你是自有部署，Fork 不要填写
地址：'/'

# 自有部署后台登录密码
密码：你好吗1851.

# 自有部署启动端口
端口：7777

# 收录通知邮箱
电子邮件：''

# 自有部署邮件通知系统
邮件配置：
  主机：smtp.mxhichina.com
  端口：465
  安全：真
  认证:
    用户： ''
    通过：''
  标题：网站收录通知
  消息：有用户提交网站收录啦

# 自有部署
XFAPI密码：''
